/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelsystem;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Toolkit;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.GrayColor;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.GregorianCalendar;
import net.proteanit.sql.DbUtils;

import java.util.*;

public final class profitloss extends javax.swing.JFrame {
Connection con=connection.dbcon();
PreparedStatement ps;
ResultSet rs;

int id,profit,result;
  int year,prevyear,prevyprof,yearprof,profinc,profpercent;
  double mIncome,mExpense,mProfit;

private void id(){
  try{
      
  
    String sql="select count(id) from kar where yil='"+String.valueOf(yearchooser.getYear())+"'";
    ps=con.prepareStatement(sql);
  
    
     //  String year=Integer.toString(yearchooser.getYear());
            
       //     ps.setString(1, year);
            
    rs=ps.executeQuery();
    
   while(rs.next()){
         String add=rs.getString(1);
          id=Integer.parseInt(add);
        
    }
    }
  catch(Exception e){
      
  }
}

private void yearprofit(){
   try{
       
   
    String sql="select sum(kari) from kar where yil='"+String.valueOf(yearchooser.getYear())+"'";
   
    ps=con.prepareStatement(sql);
  
     
     
   // String year=Integer.toString(yearchooser.getYear());
            
            //ps.setString(1, year);
            
             
    
    rs=ps.executeQuery();
    while(rs.next()){
          String add=rs.getString(1);
          //  jLabel7.setText(add);
     //    result=profit/id;
       // String add= rs.getString(result);
        lblprofit.setText(String.valueOf(add));
    }
   // int average=Integer.parseInt(lblprofit.getText());
    //int profits=average/id;
    
//    lblavg.setText(String.valueOf(profits));
    }
   catch(Exception e){
       
   }
    
}


    public void showprofit(){
      
        try{
            
       
        String sql="select * from kar";
        ps=con.prepareStatement(sql);
        
        rs=ps.executeQuery();
        
        tblprofit.setModel(DbUtils.resultSetToTableModel(rs));
        
         }
        
        catch(Exception e){
            JOptionPane.showMessageDialog( null,"Veri bulunamadi");
        }
        
    }
    
        
      public void filter(){
      try{
          
      
        
        String sql="select * from kar where ay ='"+cmbsearch.getSelectedItem()+"'";
        
        
       ps=con.prepareStatement(sql);
       //ps.setString(1,txtsearch.getText());
       
       rs=ps.executeQuery();
  
       tblprofit.setModel(DbUtils.resultSetToTableModel(rs));
     
       }
      catch(Exception e){
          
      }
       
    }
    public profitloss() {
        initComponents();
         Image ikon= Toolkit.getDefaultToolkit().getImage("F://iconss project//hotel-3245949-2737141.png");
       this.setIconImage(ikon);
        showprofit();
       selectPrevYear();
       selectThisYear();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblprofit = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmbsearch = new javax.swing.JComboBox();
        btnsearch = new javax.swing.JButton();
        cmbreport = new javax.swing.JComboBox();
        btnreport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnprofit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblprofit = new javax.swing.JLabel();
        yearchooser = new com.toedter.calendar.JYearChooser();
        lblinc = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblprofit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "SN", "Yıl", "Ayı", "ToplamGeliri", "ToplamGeliri", "Kar/Kayıp", "Tarih"
            }
        ));
        jScrollPane1.setViewportView(tblprofit);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Bir ayın karı/kayıpı arayın");

        cmbsearch.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cmbsearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" }));

        btnsearch.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnsearch.setText("Arayın");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        cmbreport.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cmbreport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yil Raporu", "Ay Raporu" }));

        btnreport.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnreport.setText("REPORT");
        btnreport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnreportMouseClicked(evt);
            }
        });
        btnreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnreport, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbreport, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cmbsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsearch))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(cmbsearch)
                    .addComponent(cmbreport)
                    .addComponent(btnreport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ARADIĞINIZ YILI SEÇİN");

        btnprofit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnprofit.setText("KAR/KAYIP ARAYIN");
        btnprofit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprofitMouseClicked(evt);
            }
        });
        btnprofit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BU YILIN ORTALAMA KAR/KAYIPI:");

        lblprofit.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblprofit.setForeground(new java.awt.Color(255, 255, 255));
        lblprofit.setText("jLabel2");

        lblinc.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblinc.setForeground(new java.awt.Color(255, 255, 255));
        lblinc.setText("jLabel2");

        jButton4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton4.setText("YIL KARI GÖSTER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(yearchooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnprofit)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblinc)
                            .addComponent(lblprofit))
                        .addGap(31, 31, 31)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearchooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblprofit)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblinc))
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)))
                        .addComponent(btnprofit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("F:\\iconss project\\add-list-xxl.png")); // NOI18N
        jButton1.setText("KAR/KAYIP HESAPLAMAYA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("F:\\iconss project\\delete.png")); // NOI18N
        jButton2.setText("SİLİN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("F:\\iconss project\\Text-Edit-icon.png")); // NOI18N
        jButton3.setText("GÜNCELLEMESİNE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("KAR.KAYIP BİLGİSİ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel6)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
this.setVisible(false);
            // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
 filter();        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
kar k= new kar();
k.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnprofitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofitActionPerformed
try{                                          
    id();
    yearprofit();
    
    String sql1="select *from yilkari where yil='"+yearchooser.getYear()+"'";
    ps=con.prepareStatement(sql1);
    
    rs=ps.executeQuery();
    
    if(rs.next()){
        JOptionPane.showMessageDialog(null, yearchooser.getYear()+"'in karı daha önce kaydedildi");
    }
    else{
        
    
    
    try{
        String sql="Insert into yilkari (yil,kari) values(?,?)";
        
        ps=con.prepareStatement(sql);
        
        // String year=Integer.toString(yearchooser.getYear());
        ps.setString(1,String.valueOf(yearchooser.getYear()));
        ps.setString(2,lblprofit.getText());
        
        ps.executeUpdate();
        
        // while(rs.next()){
        JOptionPane.showMessageDialog(null, "Bu yılın karı başarıyla kaydedildi");
        //  }
        
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
    }
    
// TODO add your handling code here:
}}   
catch(SQLException ex){
        Logger.getLogger(profitloss.class.getName()).log(Level.SEVERE,null, ex);
}


// TODO add your handling code here:
    }//GEN-LAST:event_btnprofitActionPerformed

    private void btnprofitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprofitMouseClicked
      // TODO add your handling code here:
    }//GEN-LAST:event_btnprofitMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int s= JOptionPane.showConfirmDialog(null,"Silmek istediğinize emin misiniz?","Silme işlem",JOptionPane.YES_NO_CANCEL_OPTION);        
int row=this.tblprofit.getSelectedRow();
try{
 
    if(s==0){
        
    
    String sql="Delete from kar where id='"+tblprofit.getModel().getValueAt(row, 0)+"'";
    ps=con.prepareStatement(sql);
    
    ps.execute();
    
    JOptionPane.showMessageDialog(null, "Silme işlemi başarıyla tamamlandı");
     showprofit();
     }
    else{
        
    }
    
}

catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int row=this.tblprofit.getSelectedRow();
kar k= new kar();

try{
//    k.yearchooser.setYear(Integer.parseInt(tblprofit.getModel().getValueAt(row, 1).toString()));
 //   k.cmbmonth.setSelectedItem(tblprofit.getModel().getValueAt(row, 2).toString());
    k.txtincome.setText(tblprofit.getModel().getValueAt(row, 3).toString());
    k.txtexpenses.setText(tblprofit.getModel().getValueAt(row, 4).toString());
    k.txtprofit.setText(tblprofit.getModel().getValueAt(row, 5).toString());
  
    Date dt1= new SimpleDateFormat("YYYY-MM-DD").parse((String)tblprofit.getModel().getValueAt(row,6));
   // k.dtdate.setDate(dt1);
 
    
    dispose();
    k.setVisible(true);
    k.btnadd.setVisible(false);
    k.btnupdate.setVisible(true);    
    

}
catch(Exception e){
    
}
    
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void monthincome(){
    try {
        String sql="select toplamgeliri from kar where ay='"+LocalDate.now().getMonth()+"'";
        ps=con.prepareStatement(sql);
        
        rs=ps.executeQuery();
        
        while(rs.next()){
            String add=rs.getString(1);
            mIncome=Double.parseDouble(add);
            
        }
    } catch (SQLException ex) {
        Logger.getLogger(profitloss.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }
    
      private void monthexpense(){
    try {
        String sql="select toplamgideri from kar where ay='"+LocalDate.now().getMonth()+"'";
        ps=con.prepareStatement(sql);
        
        rs=ps.executeQuery();
        
        while(rs.next()){
            String add=rs.getString(1);
            mExpense=Double.parseDouble(add);
            
        }
        mProfit=mIncome-mExpense;
        
    } catch (SQLException ex) {
        Logger.getLogger(profitloss.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }
    
    private void btnreportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreportMouseClicked
      monthincome();
        
        JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File("Kar Raporu.pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if(cmbreport.getSelectedItem()=="Ay Raporu"){

            if (dialogResult==JFileChooser.APPROVE_OPTION){
                String filePath = dialog.getSelectedFile().getPath();

                try {

                    SimpleDateFormat dateFormatss = new SimpleDateFormat("YYY-MMM-DDD");

                    String sql ="select * from kar where ay='"+LocalDate.now().getMonth().toString()+"'";

                                ps=con.prepareStatement(sql);
                    rs=ps.executeQuery();

                    Document myDocument = new Document();
                    PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filePath));
                    PdfPTable table = new PdfPTable(6);
                    PdfPTable table1 = new PdfPTable(4);
                    myDocument.open();

                    float[] columnWidths = new float[] {5,8,7,7,7,5};
                    table.setWidths(columnWidths);

                    float[] columnWidthss = new float[] {7,8,7,8};
                    table1.setWidths(columnWidthss);

                    table.setWidthPercentage(100); //set table width to 100%
                    table1.setWidthPercentage(100);
                    myDocument.add(new Paragraph(LocalDate.now().getMonth().toString()+ "'nin kar raporu",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD )));
                    myDocument.add(new Paragraph(new Date().toString()));
                    myDocument.add(new Paragraph("                                     "));

                    PdfPCell cells = new PdfPCell(new Paragraph("KAR RAPORU",FontFactory.getFont(FontFactory.TIMES_ROMAN,16,Font.BOLD,BaseColor.WHITE)));
                    cells.setColspan(6);
                    cells.setHorizontalAlignment(Element.ALIGN_CENTER);
                    cells.setBackgroundColor(BaseColor.GRAY);
                    table.addCell(cells);
                    //table.addCell(new PdfPCell(new Paragraph("ID",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD,BaseColor.RED))));
                    table.addCell(new PdfPCell(new Paragraph("SN",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD,BaseColor.BLACK))));
                    table.addCell(new PdfPCell(new Paragraph("Yil",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD,BaseColor.BLACK))));
                    table.addCell(new PdfPCell(new Paragraph("Ay",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD,BaseColor.BLACK))));
                    table.addCell(new PdfPCell(new Paragraph("ToplamGeliri",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD,BaseColor.BLACK))));
                    table.addCell(new PdfPCell(new Paragraph("ToplamGideri",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD,BaseColor.BLACK))));
                    table.addCell(new PdfPCell(new Paragraph("Kar",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD,BaseColor.BLACK))));


                    //table.addCell(cell);
                    while(rs.next())
                    {

                        //            String ids= rs.getString(1) ;
                        //            table.addCell(new PdfPCell(new Phrase(ids)));
                        String ids= rs.getString("id") ;
                        table.addCell(new PdfPCell(new Phrase(ids)));

                        String cust= rs.getString("yil") ;
                        table.addCell(new PdfPCell(new Phrase(cust)));

                        String addd= rs.getString("ay") ;
                        table.addCell(new PdfPCell(new Phrase(addd)));

                        String qt= rs.getString("toplamgeliri") ;
                        table.addCell(new PdfPCell(new Phrase(qt)));

                        String costs= rs.getString("toplamgideri") ;
                        table.addCell(new PdfPCell(new Phrase(costs)));

                        String tt= rs.getString("kari") ;
                        table.addCell(new PdfPCell(new Phrase(tt)));

                       
                    }

                    myDocument.add(table);
                    myDocument.add(new Paragraph("                                     "));
                    myDocument.add(new Paragraph("                                     "));

            /*        /// TABLE LABAAD
                    PdfPCell cellss = new PdfPCell(new Paragraph("KAR",FontFactory.getFont(FontFactory.TIMES_ROMAN,16,Font.BOLD,BaseColor.WHITE)));
                    cellss.setColspan(4);
                    cellss.setHorizontalAlignment(Element.ALIGN_CENTER);
                    cellss.setBackgroundColor(BaseColor.ORANGE);
                    table1.addCell(cellss);
                      table1.addCell(new PdfPCell(new Paragraph("Yil",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD,BaseColor.BLUE))));
                    table1.addCell(new PdfPCell(new Paragraph("Ay",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD,BaseColor.BLUE))));
                    table1.addCell(new PdfPCell(new Phrase(String.valueOf(String.valueOf(LocalDate.now().getYear()))))); 
                      table1.addCell(new PdfPCell(new Phrase(LocalDate.now().getMonth().toString())));    
                    table1.addCell(new PdfPCell(new Phrase(String.valueOf(mIncome))));
                                 table1.addCell(new PdfPCell(new Phrase(String.valueOf(mExpense))));
                                   table1.addCell(new PdfPCell(new Phrase(String.valueOf(mProfit))));
                                 */
                 
                                 myDocument.add(table1);
                    myDocument.add(new Paragraph("                                     "));
                    myDocument.add(new Paragraph("                                     "));
                    myDocument.add(new Paragraph("                                     "));
                    myDocument.add(new Paragraph("                                     "));
                    myDocument.add(new Paragraph("                                     "));
                    myDocument.add(new Paragraph("                                     "));
                    myDocument.add(new Paragraph("         Imza :______________________                            "));

                    myDocument.close();
                    JOptionPane.showMessageDialog(null,"Rapor başarıyla oluşturuldu");

                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);

                }
                finally {

                    try{
                        rs.close();
                        ps.close();

                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null,e);

                    }
                }}

            }

            else if(cmbreport.getSelectedItem()=="Yil Raporu"){
                if (dialogResult==JFileChooser.APPROVE_OPTION){
                    String filePath = dialog.getSelectedFile().getPath();

                    try {

                        SimpleDateFormat dateFormatss = new SimpleDateFormat("YYYY-MMM-DDD");

                        String sql ="select * from yilkari where yil ='"+String.valueOf(LocalDate.now().getYear())+"' ";

                        ps=con.prepareStatement(sql);
                        rs=ps.executeQuery();

                        Document myDocument = new Document();
                        PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filePath));
                        PdfPTable table = new PdfPTable(3);
                        PdfPTable table1 = new PdfPTable(3);
                        myDocument.open();

                        float[] columnWidths = new float[] {5,8,6};
                        table.setWidths(columnWidths);

                        float[] columnWidthss = new float[] {7,8,6};
                        table1.setWidths(columnWidthss);

                        table.setWidthPercentage(100); //set table width to 100%
                        table1.setWidthPercentage(100);
                        myDocument.add(new Paragraph(String.valueOf(LocalDate.now().getYear())+ "'nin kar raporu",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD )));
                        myDocument.add(new Paragraph(new Date().toString()));
                        myDocument.add(new Paragraph("                                     "));

                        PdfPCell cells = new PdfPCell(new Paragraph("KAR",FontFactory.getFont(FontFactory.TIMES_ROMAN,16,Font.BOLD,BaseColor.WHITE)));
                        cells.setColspan(3);
                        cells.setHorizontalAlignment(Element.ALIGN_CENTER);
                        cells.setBackgroundColor(BaseColor.GRAY);
                        table.addCell(cells);
                        table.addCell(new PdfPCell(new Paragraph("SN",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD,BaseColor.RED))));
                        table.addCell(new PdfPCell(new Paragraph("Yil",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD,BaseColor.BLACK))));
                        table.addCell(new PdfPCell(new Paragraph("Kari",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD,BaseColor.BLACK))));
                       

                        //table.addCell(cell);
                        while(rs.next())
                        {

                            //            String ids= rs.getString(1) ;
                            //            table.addCell(new PdfPCell(new Phrase(ids)));
                            String ids= rs.getString("id") ;
                            table.addCell(new PdfPCell(new Phrase(ids)));

                            String cust= rs.getString("yil") ;
                            table.addCell(new PdfPCell(new Phrase(cust)));

                            String addd= rs.getString("kari") ;
                            table.addCell(new PdfPCell(new Phrase(addd)));

             

                        }

                        myDocument.add(table);
                        myDocument.add(new Paragraph("                                     "));
                        myDocument.add(new Paragraph("                                     "));

                        /// TABLE LABAAD
                        PdfPCell cellss = new PdfPCell(new Paragraph("KAR",FontFactory.getFont(FontFactory.TIMES_ROMAN,16,Font.BOLD,BaseColor.WHITE)));
                        cellss.setColspan(3);
                        cellss.setHorizontalAlignment(Element.ALIGN_CENTER);
                        cellss.setBackgroundColor(BaseColor.ORANGE);
                        table1.addCell(cellss);
                    table1.addCell(new PdfPCell(new Paragraph("Yil",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD,BaseColor.BLUE))));
                        table1.addCell(new PdfPCell(new Paragraph("Kari",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD,BaseColor.BLUE))));
                                                table1.addCell(new PdfPCell(new Paragraph("Karin Artisi",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD,BaseColor.BLUE))));           
                        table1.addCell(new PdfPCell(new Phrase(String.valueOf(LocalDate.now().getYear()))));
                                table1.addCell(new PdfPCell(new Phrase(lblprofit.getText())));
                                table1.addCell(new PdfPCell(new Phrase(lblinc.getText())));
                        myDocument.add(table1);
                        myDocument.add(new Paragraph("                                     "));
                        myDocument.add(new Paragraph("                                     "));
                        myDocument.add(new Paragraph("                                     "));
                        myDocument.add(new Paragraph("                                     "));
                        myDocument.add(new Paragraph("                                     "));
                        myDocument.add(new Paragraph("                                     "));
                        myDocument.add(new Paragraph("         Signiture :______________________                            "));

                        myDocument.close();
                        JOptionPane.showMessageDialog(null,"Rapor başarıyla oluşturuldu");

                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null,e);

                    }
                    finally {

                        try{
                            rs.close();
                            ps.close();

                        }
                        catch(Exception e){
                            JOptionPane.showMessageDialog(null,e);

                        }
                    }}
                }
            }

            /**
            * @param args the command line arguments
            */
            private void counts(){
                try{

                    String sql ="select count(calisID) from calisanlar";

                    ps=con.prepareStatement(sql);

                    rs=ps.executeQuery();
                    while(rs.next()){
                        String add2 =rs.getString(1);
                        //                    lblcount.setText(add2);

                    }

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "No Data");
                }
                finally {

                    try{

                        rs.close();
                        ps.close();

                    }
                    catch(Exception e){

                    }
                }
            }
            private void showdata(){
                try{
                    String sql ="select * from gider";
                    ps = con.prepareStatement(sql);
                    rs = ps.executeQuery();
                    //                jTable1.setModel(DbUtils.resultSetToTableModel(rs));

                } catch(Exception e){

                    JOptionPane.showMessageDialog(null, e);

                }

            }

            
              private void selectPrevYear(){
       
        
              
        try {
                int year = LocalDate.now().getYear();
         int prevyear=year-1;  
             String sql1="Select kari from yilkari where yil=?";
            ps=con.prepareStatement(sql1);
            ps.setString(1, String.valueOf(prevyear));
            rs=ps.executeQuery();
            
      while(rs.next()){   
          
        String add= rs.getString(1);
            
            prevyprof+=Integer.parseInt(add);
            
           }
     //  jLabel11.setText(String.valueOf(prevyprof));
            
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
     }
     
   
     
     private void selectThisYear(){
      try{
         year = LocalDate.now().getYear();
     
        String sql="select kari from yilkari where yil=?";
   
        
        ps=con.prepareStatement(sql);
         ps.setString(1, String.valueOf(year));
         
         
      
        
         
        rs=ps.executeQuery();
        
          while(rs.next()){   
          
        String add= rs.getString(1);
            
           yearprof=Integer.parseInt(add);
            
           }
            profinc=yearprof-prevyprof;
            
             profpercent=(profinc/yearprof)*100;
         
         lblinc.setText(String.valueOf(profpercent));
   
      }
      
      catch(Exception e){
          
      }
        
    }
    
            
            
            /*  private void filter(){
                try{
                    //                String sql ="select * from employeepay where months ='"+cmbmonth.getSelectedItem()+"'";
                    //                ps = con.prepareStatement(sql);
                    rs = ps.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                    jPanel2.setVisible(true);
                } catch(Exception e){

                    JOptionPane.showMessageDialog(null, e);

                }

            }*/
            private void avrgexam(){

                try{

                    String sql ="select sum(aldigi) from gider where yil ='"+String.valueOf(LocalDate.now().getYear())+"' and ay='"+LocalDate.now().getMonth().toString()+"'";

                    ps=con.prepareStatement(sql);

                    rs=ps.executeQuery();
                    while(rs.next()){
                        String add1 =rs.getString(1);
                        //                    lblsum.setText(add1);

                    }
                    //              jPanel2.setVisible(true);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "No Data");
                }
                finally {

                    try{

                        rs.close();
                        ps.close();

                    }
                    catch(Exception e){

                    }
                }
    }//GEN-LAST:event_btnreportMouseClicked

    private void btnreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportActionPerformed

    }//GEN-LAST:event_btnreportActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.setVisible(false);
        yearprof yp = new yearprof();
yp.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profitloss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profitloss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profitloss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profitloss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profitloss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnprofit;
    private javax.swing.JButton btnreport;
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox cmbreport;
    private javax.swing.JComboBox cmbsearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblinc;
    private javax.swing.JLabel lblprofit;
    private javax.swing.JTable tblprofit;
    private com.toedter.calendar.JYearChooser yearchooser;
    // End of variables declaration//GEN-END:variables
}
